# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600

  config.vm.define :K2 do |k2|
    DefineMachineEnvironment k2, "K2", "1024"
    k2.vm.hostname = "K2"
    k2.vm.box = "bento/ubuntu-18.04"
    k2.vm.network :private_network, ip: "10.1.3.201"
    k2.vm.network :forwarded_port, guest: "3306", host: "13306", host_ip: "127.0.0.1"
    k2.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      export PATH=$HOME/.local/bin:$PATH
      sudo apt-get update
      # sudo apt-get install ubuntu-desktop
      sudo apt-get install -y python3-pip
      pip3 install --upgrade pip
      hash -r pip
      pip3 install --user --upgrade tensorflow
      pip3 install opencv-python
      cd
      git clone https://github.com/thtrieu/darkflow.git --depth 1
      cd darkflow
      pip3 install --user Cython
      sudo apt-get install libsm6 libxext6
      sudo apt-get install libfontconfig1 libxrender1
      python3 setup.py build_ext --inplace
    SHELL
  end

  ## Define macros
  def DefineMachineEnvironment(tmp, virtualbox_name, use_memory)
    tmp.vm.provider "virtualbox" do |vbox|
      vbox.name   = virtualbox_name
      vbox.memory = use_memory
      ## vbox.gui = true
    end
  end
end

